# Generated by Django 2.2.10 on 2020-06-09 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_auto_20200604_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('setar_nfe', 'Usuário pode alterar parâmetro NF-e'), ('permissao2', 'Permissão 2'), ('permissao3', 'Permissão 3'))},
        ),
    ]
