# Generated by Django 2.2.10 on 2020-06-10 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_auto_20200609_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('setar_nfe', 'Usuário pode alterar parâmetro NF-e'), ('ver_dashboard', 'Pode visualizar o dashboard'), ('permissao3', 'Permissão 3'))},
        ),
    ]
