# Generated by Django 2.2.13 on 2020-06-23 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_auto_20200609_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdopedido',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.Venda'),
        ),
    ]
