# Generated by Django 2.2.13 on 2020-06-28 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('vendas', '0007_auto_20200623_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemdopedido',
            options={'verbose_name_plural': 'Itens do Pedido'},
        ),
        migrations.AlterUniqueTogether(
            name='itemdopedido',
            unique_together={('venda', 'produto')},
        ),
    ]
