# Generated by Django 2.2.10 on 2020-06-10 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_auto_20200603_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('deletar_clientes', 'Deletar Clientes'),)},
        ),
    ]
