# Generated by Django 2.2.10 on 2020-06-10 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_auto_20200609_2134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('excluir_clientes', 'Deletar Clientes'),)},
        ),
    ]
