# Generated by Django 2.2.10 on 2020-06-10 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_auto_20200609_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('excluir_clientes', 'Excluir Clientes'),)},
        ),
    ]
