# Generated by Django 2.2.10 on 2020-06-10 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_auto_20200609_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('excluir_clientes', 'Excluir Clientes'), ('sumir_clientes', 'Sumir com clientes'))},
        ),
    ]
